### ISSUE TITLE
Add boxes near the storage wall

### ISSUE THREAD

**Issue by isRyven** [realkemon/home#10]
Since you have added back boxes near the spawn, which i think is a good idea (i have no clue why we didn't suggest you this back when we tested the map), how about adding the crates also near the storage wall as it was in original map? After playing the map on the server with real players these things kinda become more obvious, i saw allies, whilst defending the dynamite, are forced to fall back and hide behind the hills, which makes things harder for them, the boxes would ease the process. Same goes for axis when they try to defend the transmitter, while counter the allies are coming from spawn, boxes help to get behind and have a little break while reloading or throwing nade. And overall this will make path looking a bit more detailed and busy, as the space is quite empty right now. Hmm i wonder if adding tank or such vehicle somewhere near transmitter would make it looking interesting...

**Comment by realkemon** [comment]
Oh wow, yes. They are also missing.
To be honest, yesterday when I flew around etl_frostbite to take some screenshots for the readme, I've noticed quite a few things. In my mind the overhaul was in a much better state, but apparently not^^
