### ISSUE TITLE
etl_frostbite_v12 trees and a missing patch ground

### ISSUE THREAD

**Issue by woju** [realkemon/home#26]
In frostbite v12 trees appear wrong (banches are not transparent) and there is a patch of ground missing on ramp. In the screenshot it can be seen behind the tree, just below WARMUP:

![2021-03-17-205740-etl_frostbite_v12](https://user-images.githubusercontent.com/1550337/111538087-8b680580-876c-11eb-9849-286db44d5b8b.jpg)

v11 is OK (nice trees and rock solid ground).

Reproduced with minimal pk3 (`pak{0,1,2}.pk3`, `pak3_v2.76.pk3`, `etl_bin_v2.76.pk3` and `etl_frostbite_v12.pk3`).

ET:Legacy v2.76, Linux Mint 19.1.

**Comment by realkemon** [comment]
Thank you for reporting! Fixed in the recent release.
