### ISSUE TITLE
Bots not walking on Adlernest

### ISSUE THREAD

**Issue by sebdanielsson** [realkemon/home#27]
I'm running an ETL server with omni-bot but the bots are not walking on Adlernest v1. When going to the enemy spawn they just stand there and after a couple of seconds they all start shooting but don't move an inch. Any ideas why?

**Comment by realkemon** [comment]
My guess would be that you don't have bot files installed on the server for the map and it's too recent to have bot files shipped with ET: Legacy by default. You can reuse the original ones from Adlernest and it shouldn't cause any problems. You can find them here: http://svn.assembla.com/svn/omnibot/Enemy-Territory/0.8/et/nav/
Generally, you want to put the bot files in this directory `legacy\omni-bot\et\nav` 

If it's possible for you, then I would suggest to join the ET: Legacy Discord for real-time help with bot support. That isn't my strong suit tbh. https://discord.com/invite/UBAZFys

**Comment by sebdanielsson** [comment]
Yeah I had to copy the old files and rename them to the latest version, solved :)
