### ISSUE TITLE
Ice: Route blocked by steep hill

### ISSUE THREAD

**Issue by hazz1nen** [realkemon/home#28]
On et_ice, it's possible to walk up the hill near the south ladder in last stage. On etl_ice, it's not.

In the context of competitive play, the main effect this has is, defending is harder. It's a common situation that an Axis player manages to stay alive and get the objective, followed shortly by Allies respawn, leaving the objective carrier up with the docs while waiting for help and looking for a way out. Often Allies are able to take control of the yard again, and one possible escape route for the objective carrier is to jump over the wall. It's much harder for Allies players to chase the objective carrier when they can't quickly jump over the wall.

The original map is already one where double full-holds are never an issue in stopwatch play. This makes it even harder for Allies to hold the map for a decent amount of time. I think it would be better if the terrain of the hill was similar to the one on et_ice, where you can just walk up and get over the wall.

[Screenshot of the area in question](https://i.imgur.com/jwUftJ1.png)

**Comment by zenixje** [comment]
I agree. It's also possible on the RTCW version.

**Comment by realkemon** [comment]
Done in master. Will be included in the next release
