### ISSUE TITLE
Adlernest: add a bed and change a hill slightly

### ISSUE THREAD

**Issue by zenixje** [realkemon/home#30]
Like on Frostbite the original version had more beds behind eachother you could hide behind for a spawnkill. We don't need all those beds, but one extra bed to hide behind would be nice (on the place of the painting)

https://postimg.cc/nMwhqTFY

There is also a small edge at the allied spawn where you can hide. On the original version you can actually hide there and axis won't see you, that helps especially when axis is pushing right before their spawn.

https://postimg.cc/F11LtY1p

**Comment by realkemon** [comment]
![image](https://user-images.githubusercontent.com/8881420/135748080-b02a4723-db2e-4428-9f44-5dcae54544ea.png)
Beds have been adjusted.

**Comment by realkemon** [comment]
Hill adjusted as well.
Will be included in next version
