### ISSUE TITLE
Supply: add a option for a rifle trick near the maingate and reduce the mountain so trickshots are possible

### ISSUE THREAD

**Issue by zenixje** [realkemon/home#31]
On the original supply it's possible to hit a edge above the cave so the rifle lands on the maingate. Would be nice if it's added to this version.

https://i.postimg.cc/KjhbSwzH/2021-10-01-190115-etl-supply-v5.png

Also we had some complaints from several rifle players that it is not possible to do some trickshots over the map anymore, because the big mountain is blocking these.

**Comment by realkemon** [comment]
Done in master. Will be included in the next release.
